import subprocess
import re
from typing import Dict, Any
from pathlib import Path

class GitBranchManager:
    """Manages automatic branch creation/switching based on Kanban cards"""
    
    def __init__(self, project_path: Path):
        self.project_path = project_path
        
    def create_feature_branch_from_issue(self, issue: Dict[str, Any]) -> str:
        """Create a feature branch when card moves to 'In Progress'"""
        
        # Generate branch name from issue
        issue_number = issue['number']
        issue_title = issue['title']
        
        # Sanitize title for branch name
        branch_name = self._sanitize_branch_name(issue_title)
        branch_full_name = f"feature/#{issue_number}-{branch_name}"
        
        # Ensure we're on main/develop and up to date
        self._run_git(['checkout', 'main'])
        self._run_git(['pull', 'origin', 'main'])
        
        # Create and checkout new branch
        self._run_git(['checkout', '-b', branch_full_name])
        
        # Push branch to origin with upstream tracking
        self._run_git(['push', '-u', 'origin', branch_full_name])
        
        # Add branch name to issue comment for tracking
        self._comment_on_issue(
            issue_number, 
            f"🚀 Created feature branch: `{branch_full_name}`"
        )
        
        return branch_full_name
    
    def create_pull_request(
        self, 
        issue: Dict[str, Any], 
        branch_name: str,
        completion_summary: Dict[str, Any]
    ) -> str:
        """Create PR when card moves to 'Code Review'"""
        
        # Ensure all changes are committed
        self._run_git(['add', '-A'])
        
        # Create detailed commit message
        commit_message = self._generate_commit_message(issue, completion_summary)
        self._run_git(['commit', '-m', commit_message])
        
        # Push changes
        self._run_git(['push', 'origin', branch_name])
        
        # Create PR using GitHub CLI
        pr_body = self._generate_pr_body(issue, completion_summary)
        
        result = subprocess.run([
            'gh', 'pr', 'create',
            '--base', 'main',
            '--head', branch_name,
            '--title', f"#{issue['number']}: {issue['title']}",
            '--body', pr_body,
            '--assignee', '@me'
        ], cwd=self.project_path, capture_output=True, text=True)
        
        pr_url = result.stdout.strip()
        
        # Link PR to issue
        subprocess.run([
            'gh', 'issue', 'develop', 
            str(issue['number']),
            '--add-link', pr_url
        ], cwd=self.project_path)
        
        return pr_url
    
    def _sanitize_branch_name(self, title: str) -> str:
        """Convert issue title to valid branch name"""
        # Lowercase, replace spaces with hyphens
        branch = title.lower().replace(' ', '-')
        # Remove special characters
        branch = re.sub(r'[^a-z0-9-]', '', branch)
        # Limit length
        return branch[:50]
    
    def _run_git(self, args: list) -> subprocess.CompletedProcess:
        """Execute git command in project directory"""
        return subprocess.run(
            ['git'] + args,
            cwd=self.project_path,
            capture_output=True,
            text=True,
            check=True
        )
    
    def _generate_commit_message(self, issue: Dict, summary: Dict) -> str:
        """Generate comprehensive commit message"""
        return f"""
#{issue['number']}: {issue['title']}

Implementation Summary:
- Completed: {', '.join(summary.get('completed_tasks', []))}
- Test Coverage: {summary.get('test_coverage', 'N/A')}%
- Files Changed: {summary.get('files_changed', 0)}

Automated commit by SDLC Orchestrator
"""
    
    def _generate_pr_body(self, issue: Dict, summary: Dict) -> str:
        """Generate PR description with completion details"""
        return f"""
## Summary
Implements #{issue['number']}: {issue['title']}

## Changes Made
{chr(10).join('- ' + task for task in summary.get('completed_tasks', []))}

## Testing
- Test Coverage: {summary.get('test_coverage', 'N/A')}%
- Tests Passed: {summary.get('tests_passed', 'N/A')}
- Tests Added: {summary.get('tests_added', 0)}

## Quality Metrics
- Code Review Score: {summary.get('review_score', 'N/A')}/10
- Complexity: {summary.get('complexity', 'N/A')}
- Documentation Updated: {summary.get('docs_updated', False)}

## Checklist
- [x] Code follows project style guidelines
- [x] Tests pass locally
- [x] Documentation updated
- [ ] Human review completed

## Review Instructions
This PR was automatically generated by the SDLC Orchestrator. 
Please review for:
1. Business logic correctness
2. Performance implications
3. Security considerations
"""