import { RotateCcw, Wrench, GitPullRequest, MessageSquare, FlaskConical, AlertTriangle, Search, ArrowRight } from 'lucide-react'
import {
  renderReviewCycleSummary,
  renderRepairCycleSummary,
  renderPRReviewCycleSummary,
  renderConversationalLoopSummary,
  renderReviewIterationSummary,
  renderRepairTestCycleSummary,
  renderPRReviewPhaseSummary,
  renderTestExecutionSummary,
  renderFixCycleSummary,
  renderWarningReviewSummary,
  renderSystemicAnalysisSummary,
  renderSystemicFixSummary,
  renderStatusProgressionSummary,
} from './cycleCollapsedSummaries.jsx'

/**
 * Theme config registry keyed by cycleType string.
 * Each entry defines the visual theme and collapsed summary renderer for that cycle type.
 * Consumed by CycleContainerNode (unified dispatcher).
 */
export const CYCLE_THEME_MAP = {
  // ── Level 1 ───────────────────────────────────────────────────────────────
  review_cycle: {
    borderColor:              '#9333ea',
    borderStyle:              'solid',
    bgColor:                  'rgba(147, 51, 234, 0.14)',
    cornerColor:              'rgba(147,51,234,0.6)',
    icon:                     RotateCcw,
    countSuffix:              'iteration',
    collapsedLabel:           'Review Cycle',
    collapsedTextColor:       '#c4b5fd',
    collapsedCountColor:      '#c4b5fd',
    collapsedCountColorLight: '#6d28d9',
    collapsedWidth:           320,
    renderCollapsedSummary:   renderReviewCycleSummary,
  },
  repair_cycle: {
    borderColor:              '#d97706',
    borderStyle:              'solid',
    bgColor:                  'rgba(217, 119, 6, 0.14)',
    cornerColor:              'rgba(217,119,6,0.6)',
    icon:                     Wrench,
    countSuffix:              'test cycle',
    collapsedLabel:           'Repair Cycle',
    collapsedTextColor:       '#fcd34d',
    collapsedCountColor:      '#fcd34d',
    collapsedCountColorLight: '#92400e',
    collapsedWidth:           340,
    renderCollapsedSummary:   renderRepairCycleSummary,
  },
  pr_review_cycle: {
    borderColor:              '#0ea5e9',
    borderStyle:              'solid',
    bgColor:                  'rgba(14,165,233,0.12)',
    cornerColor:              'rgba(14,165,233,0.5)',
    icon:                     GitPullRequest,
    countSuffix:              'phase',
    collapsedLabel:           'PR Review',
    collapsedTextColor:       '#7dd3fc',
    collapsedCountColor:      '#7dd3fc',
    collapsedCountColorLight: '#0369a1',
    collapsedWidth:           300,
    renderCollapsedSummary:   renderPRReviewCycleSummary,
  },
  conversational_loop: {
    borderColor:              '#ec4899',
    borderStyle:              'solid',
    bgColor:                  'rgba(236,72,153,0.12)',
    cornerColor:              'rgba(236,72,153,0.5)',
    icon:                     MessageSquare,
    countSuffix:              'question',
    collapsedLabel:           'Conversation',
    collapsedTextColor:       '#f9a8d4',
    collapsedCountColor:      '#f9a8d4',
    collapsedCountColorLight: '#be185d',
    collapsedWidth:           280,
    renderCollapsedSummary:   renderConversationalLoopSummary,
  },

  status_progression: {
    borderColor:              '#22c55e',
    borderStyle:              'solid',
    bgColor:                  'rgba(34,197,94,0.10)',
    cornerColor:              'rgba(34,197,94,0.4)',
    icon:                     ArrowRight,
    countSuffix:              'step',
    collapsedLabel:           'Status Move',
    collapsedTextColor:       '#86efac',
    collapsedCountColor:      '#86efac',
    collapsedCountColorLight: '#166534',
    collapsedWidth:           320,
    renderCollapsedSummary:   renderStatusProgressionSummary,
  },

  // ── Level 2 ───────────────────────────────────────────────────────────────
  review_iteration: {
    borderColor:              '#9333ea',
    borderStyle:              'solid',
    bgColor:                  'rgba(147,51,234,0.06)',
    cornerColor:              'rgba(147,51,234,0.35)',
    icon:                     RotateCcw,
    countSuffix:              'event',
    collapsedLabel:           'Iteration',
    collapsedTextColor:       '#c4b5fd',
    collapsedCountColor:      '#c4b5fd',
    collapsedCountColorLight: '#6d28d9',
    collapsedWidth:           280,
    renderCollapsedSummary:   renderReviewIterationSummary,
  },
  repair_test_cycle: {
    borderColor:              '#d97706',
    borderStyle:              'solid',
    bgColor:                  'rgba(217,119,6,0.06)',
    cornerColor:              'rgba(217,119,6,0.35)',
    icon:                     Wrench,
    countSuffix:              'sub-cycle',
    collapsedLabel:           'Test Cycle',
    collapsedTextColor:       '#fcd34d',
    collapsedCountColor:      '#fcd34d',
    collapsedCountColorLight: '#92400e',
    collapsedWidth:           300,
    renderCollapsedSummary:   renderRepairTestCycleSummary,
  },
  pr_review_phase: {
    borderColor:              '#0ea5e9',
    borderStyle:              'solid',
    bgColor:                  'rgba(14,165,233,0.06)',
    cornerColor:              'rgba(14,165,233,0.35)',
    icon:                     GitPullRequest,
    countSuffix:              'event',
    collapsedLabel:           'Phase',
    collapsedTextColor:       '#7dd3fc',
    collapsedCountColor:      '#7dd3fc',
    collapsedCountColorLight: '#0369a1',
    collapsedWidth:           280,
    renderCollapsedSummary:   renderPRReviewPhaseSummary,
  },

  // ── Level 3 ───────────────────────────────────────────────────────────────
  test_execution: {
    borderColor:              '#10b981',
    borderStyle:              'solid',
    bgColor:                  'rgba(16,185,129,0.06)',
    cornerColor:              'rgba(16,185,129,0.35)',
    icon:                     FlaskConical,
    countSuffix:              'event',
    collapsedLabel:           'Test Execution',
    collapsedTextColor:       '#6ee7b7',
    collapsedCountColor:      '#6ee7b7',
    collapsedCountColorLight: '#047857',
    collapsedWidth:           260,
    renderCollapsedSummary:   renderTestExecutionSummary,
  },
  fix_cycle: {
    borderColor:              '#d97706',
    borderStyle:              'solid',
    bgColor:                  'rgba(217,119,6,0.06)',
    cornerColor:              'rgba(217,119,6,0.35)',
    icon:                     Wrench,
    countSuffix:              'fix',
    collapsedLabel:           'Fix Cycle',
    collapsedTextColor:       '#fcd34d',
    collapsedCountColor:      '#fcd34d',
    collapsedCountColorLight: '#92400e',
    collapsedWidth:           260,
    renderCollapsedSummary:   renderFixCycleSummary,
  },
  warning_review: {
    borderColor:              '#f59e0b',
    borderStyle:              'solid',
    bgColor:                  'rgba(245,158,11,0.06)',
    cornerColor:              'rgba(245,158,11,0.35)',
    icon:                     AlertTriangle,
    countSuffix:              'warning',
    collapsedLabel:           'Warning Review',
    collapsedTextColor:       '#fde68a',
    collapsedCountColor:      '#fde68a',
    collapsedCountColorLight: '#92400e',
    collapsedWidth:           260,
    renderCollapsedSummary:   renderWarningReviewSummary,
  },
  systemic_analysis: {
    borderColor:              '#8b5cf6',
    borderStyle:              'solid',
    bgColor:                  'rgba(139,92,246,0.06)',
    cornerColor:              'rgba(139,92,246,0.35)',
    icon:                     Search,
    countSuffix:              'event',
    collapsedLabel:           'Systemic Analysis',
    collapsedTextColor:       '#c4b5fd',
    collapsedCountColor:      '#c4b5fd',
    collapsedCountColorLight: '#6d28d9',
    collapsedWidth:           260,
    renderCollapsedSummary:   renderSystemicAnalysisSummary,
  },
  systemic_fix: {
    borderColor:              '#a78bfa',
    borderStyle:              'solid',
    bgColor:                  'rgba(167,139,250,0.06)',
    cornerColor:              'rgba(167,139,250,0.35)',
    icon:                     Wrench,
    countSuffix:              'fix',
    collapsedLabel:           'Systemic Fix',
    collapsedTextColor:       '#ddd6fe',
    collapsedCountColor:      '#ddd6fe',
    collapsedCountColorLight: '#047857',
    collapsedWidth:           260,
    renderCollapsedSummary:   renderSystemicFixSummary,
  },
}
