/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectMetricsRouteImport } from './routes/project-metrics'
import { Route as RecommendationReportsRouteImport } from './routes/recommendation-reports'
import { Route as PipelineRunRouteImport } from './routes/pipeline-run'
import { Route as PipelineReportsRouteImport } from './routes/pipeline-reports'
import { Route as CycleMetricsRouteImport } from './routes/cycle-metrics'
import { Route as AgentMetricsRouteImport } from './routes/agent-metrics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentExecutionExecutionIdRouteImport } from './routes/agent-execution.$executionId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectMetricsRoute = ProjectMetricsRouteImport.update({
  id: '/project-metrics',
  path: '/project-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationReportsRoute = RecommendationReportsRouteImport.update({
  id: '/recommendation-reports',
  path: '/recommendation-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRunRoute = PipelineRunRouteImport.update({
  id: '/pipeline-run',
  path: '/pipeline-run',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineReportsRoute = PipelineReportsRouteImport.update({
  id: '/pipeline-reports',
  path: '/pipeline-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleMetricsRoute = CycleMetricsRouteImport.update({
  id: '/cycle-metrics',
  path: '/cycle-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMetricsRoute = AgentMetricsRouteImport.update({
  id: '/agent-metrics',
  path: '/agent-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentExecutionExecutionIdRoute =
  AgentExecutionExecutionIdRouteImport.update({
    id: '/agent-execution/$executionId',
    path: '/agent-execution/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-metrics': typeof AgentMetricsRoute
  '/cycle-metrics': typeof CycleMetricsRoute
  '/pipeline-run': typeof PipelineRunRoute
  '/pipeline-reports': typeof PipelineReportsRoute
  '/recommendation-reports': typeof RecommendationReportsRoute
  '/project-metrics': typeof ProjectMetricsRoute
  '/projects': typeof ProjectsRoute
  '/agent-execution/$executionId': typeof AgentExecutionExecutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-metrics': typeof AgentMetricsRoute
  '/cycle-metrics': typeof CycleMetricsRoute
  '/pipeline-run': typeof PipelineRunRoute
  '/pipeline-reports': typeof PipelineReportsRoute
  '/recommendation-reports': typeof RecommendationReportsRoute
  '/project-metrics': typeof ProjectMetricsRoute
  '/projects': typeof ProjectsRoute
  '/agent-execution/$executionId': typeof AgentExecutionExecutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-metrics': typeof AgentMetricsRoute
  '/cycle-metrics': typeof CycleMetricsRoute
  '/pipeline-run': typeof PipelineRunRoute
  '/pipeline-reports': typeof PipelineReportsRoute
  '/recommendation-reports': typeof RecommendationReportsRoute
  '/project-metrics': typeof ProjectMetricsRoute
  '/projects': typeof ProjectsRoute
  '/agent-execution/$executionId': typeof AgentExecutionExecutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-metrics'
    | '/cycle-metrics'
    | '/pipeline-run'
    | '/pipeline-reports'
    | '/recommendation-reports'
    | '/project-metrics'
    | '/projects'
    | '/agent-execution/$executionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-metrics'
    | '/cycle-metrics'
    | '/pipeline-run'
    | '/pipeline-reports'
    | '/recommendation-reports'
    | '/project-metrics'
    | '/projects'
    | '/agent-execution/$executionId'
  id:
    | '__root__'
    | '/'
    | '/agent-metrics'
    | '/cycle-metrics'
    | '/pipeline-run'
    | '/pipeline-reports'
    | '/recommendation-reports'
    | '/project-metrics'
    | '/projects'
    | '/agent-execution/$executionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentMetricsRoute: typeof AgentMetricsRoute
  CycleMetricsRoute: typeof CycleMetricsRoute
  PipelineRunRoute: typeof PipelineRunRoute
  PipelineReportsRoute: typeof PipelineReportsRoute
  RecommendationReportsRoute: typeof RecommendationReportsRoute
  ProjectMetricsRoute: typeof ProjectMetricsRoute
  ProjectsRoute: typeof ProjectsRoute
  AgentExecutionExecutionIdRoute: typeof AgentExecutionExecutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-metrics': {
      id: '/project-metrics'
      path: '/project-metrics'
      fullPath: '/project-metrics'
      preLoaderRoute: typeof ProjectMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-run': {
      id: '/pipeline-run'
      path: '/pipeline-run'
      fullPath: '/pipeline-run'
      preLoaderRoute: typeof PipelineRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-reports': {
      id: '/pipeline-reports'
      path: '/pipeline-reports'
      fullPath: '/pipeline-reports'
      preLoaderRoute: typeof PipelineReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation-reports': {
      id: '/recommendation-reports'
      path: '/recommendation-reports'
      fullPath: '/recommendation-reports'
      preLoaderRoute: typeof RecommendationReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle-metrics': {
      id: '/cycle-metrics'
      path: '/cycle-metrics'
      fullPath: '/cycle-metrics'
      preLoaderRoute: typeof CycleMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-metrics': {
      id: '/agent-metrics'
      path: '/agent-metrics'
      fullPath: '/agent-metrics'
      preLoaderRoute: typeof AgentMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-execution/$executionId': {
      id: '/agent-execution/$executionId'
      path: '/agent-execution/$executionId'
      fullPath: '/agent-execution/$executionId'
      preLoaderRoute: typeof AgentExecutionExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentMetricsRoute: AgentMetricsRoute,
  CycleMetricsRoute: CycleMetricsRoute,
  PipelineRunRoute: PipelineRunRoute,
  PipelineReportsRoute: PipelineReportsRoute,
  RecommendationReportsRoute: RecommendationReportsRoute,
  ProjectMetricsRoute: ProjectMetricsRoute,
  ProjectsRoute: ProjectsRoute,
  AgentExecutionExecutionIdRoute: AgentExecutionExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
