/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationReportsRouteImport } from './routes/recommendation-reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectMetricsRouteImport } from './routes/project-metrics'
import { Route as PipelineRunRouteImport } from './routes/pipeline-run'
import { Route as PipelineReportsRouteImport } from './routes/pipeline-reports'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CycleMetricsRouteImport } from './routes/cycle-metrics'
import { Route as AgentMetricsRouteImport } from './routes/agent-metrics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetricsTokensRouteImport } from './routes/metrics/tokens'
import { Route as MetricsProjectRouteImport } from './routes/metrics/project'
import { Route as MetricsCycleRouteImport } from './routes/metrics/cycle'
import { Route as MetricsAgentRouteImport } from './routes/metrics/agent'
import { Route as AgentExecutionExecutionIdRouteImport } from './routes/agent-execution.$executionId'

const RecommendationReportsRoute = RecommendationReportsRouteImport.update({
  id: '/recommendation-reports',
  path: '/recommendation-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectMetricsRoute = ProjectMetricsRouteImport.update({
  id: '/project-metrics',
  path: '/project-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRunRoute = PipelineRunRouteImport.update({
  id: '/pipeline-run',
  path: '/pipeline-run',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineReportsRoute = PipelineReportsRouteImport.update({
  id: '/pipeline-reports',
  path: '/pipeline-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleMetricsRoute = CycleMetricsRouteImport.update({
  id: '/cycle-metrics',
  path: '/cycle-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMetricsRoute = AgentMetricsRouteImport.update({
  id: '/agent-metrics',
  path: '/agent-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsTokensRoute = MetricsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => MetricsRoute,
} as any)
const MetricsProjectRoute = MetricsProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => MetricsRoute,
} as any)
const MetricsCycleRoute = MetricsCycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => MetricsRoute,
} as any)
const MetricsAgentRoute = MetricsAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => MetricsRoute,
} as any)
const AgentExecutionExecutionIdRoute =
  AgentExecutionExecutionIdRouteImport.update({
    id: '/agent-execution/$executionId',
    path: '/agent-execution/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-metrics': typeof AgentMetricsRoute
  '/cycle-metrics': typeof CycleMetricsRoute
  '/dashboard': typeof DashboardRoute
  '/metrics': typeof MetricsRouteWithChildren
  '/pipeline-reports': typeof PipelineReportsRoute
  '/pipeline-run': typeof PipelineRunRoute
  '/project-metrics': typeof ProjectMetricsRoute
  '/projects': typeof ProjectsRoute
  '/recommendation-reports': typeof RecommendationReportsRoute
  '/agent-execution/$executionId': typeof AgentExecutionExecutionIdRoute
  '/metrics/agent': typeof MetricsAgentRoute
  '/metrics/cycle': typeof MetricsCycleRoute
  '/metrics/project': typeof MetricsProjectRoute
  '/metrics/tokens': typeof MetricsTokensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-metrics': typeof AgentMetricsRoute
  '/cycle-metrics': typeof CycleMetricsRoute
  '/dashboard': typeof DashboardRoute
  '/metrics': typeof MetricsRouteWithChildren
  '/pipeline-reports': typeof PipelineReportsRoute
  '/pipeline-run': typeof PipelineRunRoute
  '/project-metrics': typeof ProjectMetricsRoute
  '/projects': typeof ProjectsRoute
  '/recommendation-reports': typeof RecommendationReportsRoute
  '/agent-execution/$executionId': typeof AgentExecutionExecutionIdRoute
  '/metrics/agent': typeof MetricsAgentRoute
  '/metrics/cycle': typeof MetricsCycleRoute
  '/metrics/project': typeof MetricsProjectRoute
  '/metrics/tokens': typeof MetricsTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-metrics': typeof AgentMetricsRoute
  '/cycle-metrics': typeof CycleMetricsRoute
  '/dashboard': typeof DashboardRoute
  '/metrics': typeof MetricsRouteWithChildren
  '/pipeline-reports': typeof PipelineReportsRoute
  '/pipeline-run': typeof PipelineRunRoute
  '/project-metrics': typeof ProjectMetricsRoute
  '/projects': typeof ProjectsRoute
  '/recommendation-reports': typeof RecommendationReportsRoute
  '/agent-execution/$executionId': typeof AgentExecutionExecutionIdRoute
  '/metrics/agent': typeof MetricsAgentRoute
  '/metrics/cycle': typeof MetricsCycleRoute
  '/metrics/project': typeof MetricsProjectRoute
  '/metrics/tokens': typeof MetricsTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-metrics'
    | '/cycle-metrics'
    | '/dashboard'
    | '/metrics'
    | '/pipeline-reports'
    | '/pipeline-run'
    | '/project-metrics'
    | '/projects'
    | '/recommendation-reports'
    | '/agent-execution/$executionId'
    | '/metrics/agent'
    | '/metrics/cycle'
    | '/metrics/project'
    | '/metrics/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-metrics'
    | '/cycle-metrics'
    | '/dashboard'
    | '/metrics'
    | '/pipeline-reports'
    | '/pipeline-run'
    | '/project-metrics'
    | '/projects'
    | '/recommendation-reports'
    | '/agent-execution/$executionId'
    | '/metrics/agent'
    | '/metrics/cycle'
    | '/metrics/project'
    | '/metrics/tokens'
  id:
    | '__root__'
    | '/'
    | '/agent-metrics'
    | '/cycle-metrics'
    | '/dashboard'
    | '/metrics'
    | '/pipeline-reports'
    | '/pipeline-run'
    | '/project-metrics'
    | '/projects'
    | '/recommendation-reports'
    | '/agent-execution/$executionId'
    | '/metrics/agent'
    | '/metrics/cycle'
    | '/metrics/project'
    | '/metrics/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentMetricsRoute: typeof AgentMetricsRoute
  CycleMetricsRoute: typeof CycleMetricsRoute
  DashboardRoute: typeof DashboardRoute
  MetricsRoute: typeof MetricsRouteWithChildren
  PipelineReportsRoute: typeof PipelineReportsRoute
  PipelineRunRoute: typeof PipelineRunRoute
  ProjectMetricsRoute: typeof ProjectMetricsRoute
  ProjectsRoute: typeof ProjectsRoute
  RecommendationReportsRoute: typeof RecommendationReportsRoute
  AgentExecutionExecutionIdRoute: typeof AgentExecutionExecutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendation-reports': {
      id: '/recommendation-reports'
      path: '/recommendation-reports'
      fullPath: '/recommendation-reports'
      preLoaderRoute: typeof RecommendationReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-metrics': {
      id: '/project-metrics'
      path: '/project-metrics'
      fullPath: '/project-metrics'
      preLoaderRoute: typeof ProjectMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-run': {
      id: '/pipeline-run'
      path: '/pipeline-run'
      fullPath: '/pipeline-run'
      preLoaderRoute: typeof PipelineRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-reports': {
      id: '/pipeline-reports'
      path: '/pipeline-reports'
      fullPath: '/pipeline-reports'
      preLoaderRoute: typeof PipelineReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle-metrics': {
      id: '/cycle-metrics'
      path: '/cycle-metrics'
      fullPath: '/cycle-metrics'
      preLoaderRoute: typeof CycleMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-metrics': {
      id: '/agent-metrics'
      path: '/agent-metrics'
      fullPath: '/agent-metrics'
      preLoaderRoute: typeof AgentMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/tokens': {
      id: '/metrics/tokens'
      path: '/tokens'
      fullPath: '/metrics/tokens'
      preLoaderRoute: typeof MetricsTokensRouteImport
      parentRoute: typeof MetricsRoute
    }
    '/metrics/project': {
      id: '/metrics/project'
      path: '/project'
      fullPath: '/metrics/project'
      preLoaderRoute: typeof MetricsProjectRouteImport
      parentRoute: typeof MetricsRoute
    }
    '/metrics/cycle': {
      id: '/metrics/cycle'
      path: '/cycle'
      fullPath: '/metrics/cycle'
      preLoaderRoute: typeof MetricsCycleRouteImport
      parentRoute: typeof MetricsRoute
    }
    '/metrics/agent': {
      id: '/metrics/agent'
      path: '/agent'
      fullPath: '/metrics/agent'
      preLoaderRoute: typeof MetricsAgentRouteImport
      parentRoute: typeof MetricsRoute
    }
    '/agent-execution/$executionId': {
      id: '/agent-execution/$executionId'
      path: '/agent-execution/$executionId'
      fullPath: '/agent-execution/$executionId'
      preLoaderRoute: typeof AgentExecutionExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MetricsRouteChildren {
  MetricsAgentRoute: typeof MetricsAgentRoute
  MetricsCycleRoute: typeof MetricsCycleRoute
  MetricsProjectRoute: typeof MetricsProjectRoute
  MetricsTokensRoute: typeof MetricsTokensRoute
}

const MetricsRouteChildren: MetricsRouteChildren = {
  MetricsAgentRoute: MetricsAgentRoute,
  MetricsCycleRoute: MetricsCycleRoute,
  MetricsProjectRoute: MetricsProjectRoute,
  MetricsTokensRoute: MetricsTokensRoute,
}

const MetricsRouteWithChildren =
  MetricsRoute._addFileChildren(MetricsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentMetricsRoute: AgentMetricsRoute,
  CycleMetricsRoute: CycleMetricsRoute,
  DashboardRoute: DashboardRoute,
  MetricsRoute: MetricsRouteWithChildren,
  PipelineReportsRoute: PipelineReportsRoute,
  PipelineRunRoute: PipelineRunRoute,
  ProjectMetricsRoute: ProjectMetricsRoute,
  ProjectsRoute: ProjectsRoute,
  RecommendationReportsRoute: RecommendationReportsRoute,
  AgentExecutionExecutionIdRoute: AgentExecutionExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
