/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PipelineRunDebugRouteImport } from './routes/pipeline-run-debug'
import { Route as PipelineRunRouteImport } from './routes/pipeline-run'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentExecutionExecutionIdRouteImport } from './routes/agent-execution.$executionId'
import { Route as AgentMetricsRouteImport } from './routes/agent-metrics'
import { Route as CycleMetricsRouteImport } from './routes/cycle-metrics'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRunDebugRoute = PipelineRunDebugRouteImport.update({
  id: '/pipeline-run-debug',
  path: '/pipeline-run-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRunRoute = PipelineRunRouteImport.update({
  id: '/pipeline-run',
  path: '/pipeline-run',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentExecutionExecutionIdRoute =
  AgentExecutionExecutionIdRouteImport.update({
    id: '/agent-execution/$executionId',
    path: '/agent-execution/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentMetricsRoute = AgentMetricsRouteImport.update({
  id: '/agent-metrics',
  path: '/agent-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleMetricsRoute = CycleMetricsRouteImport.update({
  id: '/cycle-metrics',
  path: '/cycle-metrics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pipeline-run': typeof PipelineRunRoute
  '/pipeline-run-debug': typeof PipelineRunDebugRoute
  '/projects': typeof ProjectsRoute
  '/agent-execution/$executionId': typeof AgentExecutionExecutionIdRoute
  '/agent-metrics': typeof AgentMetricsRoute
  '/cycle-metrics': typeof CycleMetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pipeline-run': typeof PipelineRunRoute
  '/pipeline-run-debug': typeof PipelineRunDebugRoute
  '/projects': typeof ProjectsRoute
  '/agent-execution/$executionId': typeof AgentExecutionExecutionIdRoute
  '/agent-metrics': typeof AgentMetricsRoute
  '/cycle-metrics': typeof CycleMetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pipeline-run': typeof PipelineRunRoute
  '/pipeline-run-debug': typeof PipelineRunDebugRoute
  '/projects': typeof ProjectsRoute
  '/agent-execution/$executionId': typeof AgentExecutionExecutionIdRoute
  '/agent-metrics': typeof AgentMetricsRoute
  '/cycle-metrics': typeof CycleMetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pipeline-run'
    | '/pipeline-run-debug'
    | '/projects'
    | '/agent-execution/$executionId'
    | '/agent-metrics'
    | '/cycle-metrics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pipeline-run'
    | '/pipeline-run-debug'
    | '/projects'
    | '/agent-execution/$executionId'
    | '/agent-metrics'
    | '/cycle-metrics'
  id:
    | '__root__'
    | '/'
    | '/pipeline-run'
    | '/pipeline-run-debug'
    | '/projects'
    | '/agent-execution/$executionId'
    | '/agent-metrics'
    | '/cycle-metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PipelineRunRoute: typeof PipelineRunRoute
  PipelineRunDebugRoute: typeof PipelineRunDebugRoute
  ProjectsRoute: typeof ProjectsRoute
  AgentExecutionExecutionIdRoute: typeof AgentExecutionExecutionIdRoute
  AgentMetricsRoute: typeof AgentMetricsRoute
  CycleMetricsRoute: typeof CycleMetricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-run-debug': {
      id: '/pipeline-run-debug'
      path: '/pipeline-run-debug'
      fullPath: '/pipeline-run-debug'
      preLoaderRoute: typeof PipelineRunDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-run': {
      id: '/pipeline-run'
      path: '/pipeline-run'
      fullPath: '/pipeline-run'
      preLoaderRoute: typeof PipelineRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-execution/$executionId': {
      id: '/agent-execution/$executionId'
      path: '/agent-execution/$executionId'
      fullPath: '/agent-execution/$executionId'
      preLoaderRoute: typeof AgentExecutionExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-metrics': {
      id: '/agent-metrics'
      path: '/agent-metrics'
      fullPath: '/agent-metrics'
      preLoaderRoute: typeof AgentMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle-metrics': {
      id: '/cycle-metrics'
      path: '/cycle-metrics'
      fullPath: '/cycle-metrics'
      preLoaderRoute: typeof CycleMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PipelineRunRoute: PipelineRunRoute,
  PipelineRunDebugRoute: PipelineRunDebugRoute,
  ProjectsRoute: ProjectsRoute,
  AgentExecutionExecutionIdRoute: AgentExecutionExecutionIdRoute,
  AgentMetricsRoute: AgentMetricsRoute,
  CycleMetricsRoute: CycleMetricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
